# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 05:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import zipline_app.models.zipline_app.side
import zipline_app.utils


class Migration(migrations.Migration):

    replaces = [('zipline_app', '0001_initial'), ('zipline_app', '0002_auto_20170321_1047'), ('zipline_app', '0003_account_account_name'), ('zipline_app', '0004_auto_20170327_1514'), ('zipline_app', '0005_auto_20170327_1515'), ('zipline_app', '0006_orderhistory'), ('zipline_app', '0007_orderhistory_ed_date'), ('zipline_app', '0008_auto_20170327_1642'), ('zipline_app', '0009_auto_20170327_1732'), ('zipline_app', '0010_auto_20170327_1738')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_symbol', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=20, unique=True)),
                ('asset_exchange', models.CharField(max_length=200)),
                ('asset_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_text', models.CharField(blank=True, max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('fill_qty_unsigned', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty')),
                ('fill_price', zipline_app.models.zipline_app.side.PositiveFloatFieldModel(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0), zipline_app.models.zipline_app.side.validate_nonzero])),
                ('pub_date', models.DateTimeField(default=zipline_app.utils.now_minute, verbose_name='date published')),
                ('tt_order_key', models.CharField(blank=True, max_length=20)),
                ('fill_side', models.CharField(choices=[('L', 'Long'), ('S', 'Short')], default='L', max_length=1, verbose_name='Side')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_text', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(default=zipline_app.utils.now_minute, verbose_name='date published')),
                ('amount_unsigned', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty')),
                ('order_side', models.CharField(choices=[('L', 'Long'), ('S', 'Short')], default='L', max_length=1, verbose_name='Side')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Account')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Asset')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('limit_price', zipline_app.models.zipline_app.side.PositiveFloatFieldModel(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0), zipline_app.models.zipline_app.side.validate_nonzero])),
                ('order_type', models.CharField(choices=[('M', 'Market'), ('L', 'Limit')], default='M', max_length=1, verbose_name='Type')),
            ],
        ),
        migrations.AddField(
            model_name='fill',
            name='dedicated_to_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zipline_app.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='fill',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_text', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(default=zipline_app.utils.now_minute, verbose_name='date published')),
                ('amount_unsigned', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), zipline_app.models.zipline_app.side.validate_nonzero], verbose_name='Qty')),
                ('order_side', models.CharField(choices=[('L', 'Long'), ('S', 'Short')], default='L', max_length=1, verbose_name='Side')),
                ('order_type', models.CharField(choices=[('M', 'Market'), ('L', 'Limit')], default='M', max_length=1, verbose_name='Type')),
                ('limit_price', zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0), zipline_app.models.zipline_app.side.validate_nonzero])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Account')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Asset')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Order')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.OrderHistory')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date edited')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='limit_price',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0), zipline_app.models.zipline_app.side.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='order',
            name='limit_price',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0), zipline_app.models.zipline_app.side.validate_nonzero]),
        ),
    ]
