# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import zipline_app.models.zipline_app.fill


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_symbol', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=20, unique=True)),
                ('asset_exchange', models.CharField(max_length=200)),
                ('asset_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_text', models.CharField(blank=True, max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('fill_qty', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(-1000000), zipline_app.models.zipline_app.fill.validate_nonzero])),
                ('fill_price', zipline_app.models.zipline_app.fill.PositiveFloatFieldModel(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0), zipline_app.models.zipline_app.fill.validate_nonzero])),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_text', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(-1000000), zipline_app.models.zipline_app.fill.validate_nonzero])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Account')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Asset')),
            ],
        ),
    ]
