# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0001_squashed_0010_auto_20170327_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_unsigned',
            new_name='order_qty_unsigned',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='amount_unsigned',
            new_name='order_qty_unsigned',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Filled'), ('C', 'Cancelled'), ('R', 'Rejected'), ('H', 'Held')], default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Filled'), ('C', 'Cancelled'), ('R', 'Rejected'), ('H', 'Held')], default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='fill_side',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1, verbose_name='Side'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_side',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1, verbose_name='Side'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_side',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1, verbose_name='Side'),
        ),
    ]
