# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=200),
        ),
    ]
