# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0002_auto_20170321_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
