# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0003_auto_20170331_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_validity',
            field=models.CharField(choices=[('C', 'GTC order'), ('D', 'GTD order'), ('-', 'Day order')], default='C', max_length=1, verbose_name='Validity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='validity_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_validity',
            field=models.CharField(choices=[('C', 'GTC order'), ('D', 'GTD order'), ('-', 'Day order')], default='C', max_length=1, verbose_name='Validity'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='validity_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='YYYY-MM-DD', null=True),
        ),
    ]
