# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0003_auto_20170317_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='dedicated_to_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Order'),
        ),
    ]
