# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0004_fill_dedicated_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='dedicated_to_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.Order', verbose_name='Order'),
        ),
    ]
