# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0004_auto_20170331_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='validity_date',
            field=models.DateTimeField(blank=True, default=None, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='validity_date',
            field=models.DateTimeField(blank=True, default=None, help_text='YYYY-MM-DD', null=True),
        ),
    ]
