# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0004_auto_20170327_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('M', 'Market'), ('L', 'Limit')], default='M', max_length=1, verbose_name='Type'),
        ),
    ]
