# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0006_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='ed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date edited'),
        ),
    ]
