# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0007_orderhistory_ed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zipline_app.OrderHistory'),
        ),
    ]
