# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import zipline_app.models.zipline_app.side


class Migration(migrations.Migration):

    dependencies = [
        ('zipline_app', '0009_auto_20170327_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='limit_price',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0), zipline_app.models.zipline_app.side.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='limit_price',
            field=zipline_app.models.zipline_app.side.PositiveFloatFieldModel(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0), zipline_app.models.zipline_app.side.validate_nonzero]),
        ),
    ]
