# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170212_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='question_text',
            new_name='order_text',
        ),
    ]
