# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170212_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Fill',
        ),
        migrations.RenameField(
            model_name='fill',
            old_name='choice_text',
            new_name='fill_text',
        ),
    ]
