# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170212_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sid',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
