# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170212_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='fill_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fill',
            name='fill_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fill',
            name='pub_date',
            field=models.DateTimeField(default='1970-01-01 01:01:01', verbose_name='date published'),
        ),
    ]
