# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170212_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 8, 47, 50, 865854, tzinfo=utc), verbose_name='date published'),
        ),
    ]
