# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170212_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
