# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170212_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fill',
            old_name='fill_sid',
            new_name='fill_symbol',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_sid',
            new_name='order_symbol',
        ),
    ]
