# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20170213_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_sid',
            field=models.IntegerField(default=0),
        ),
    ]
